apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: shortlink
type: Opaque
stringData:
  # RDS Credentials (should use AWS Secrets Manager in production)
  RDS_USERNAME: "${RDS_USERNAME}"
  RDS_PASSWORD: "${RDS_PASSWORD}"
  
  # Redis Password (if enabled)
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
