apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shortlink-infrastructure
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/Rurutia1027/Shortlink-Backend.git 
    targetRevision: main
    path: Shortlink-AWS-Terraform/gitops/base

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
